/// Builds `assets/db/dictionary.db` — the read-only content the app ships —
/// using the DeepSeek API.
///
/// Usage:
///
///   # Generate. Resumable: rerun the same command to pick up where it stopped.
///   dart run tool/generate_dictionary.dart generate --words tool/words_30k.txt
///
///   # Try the prompt on a handful of words first.
///   dart run tool/generate_dictionary.dart generate \
///       --words tool/words_sample.txt --limit 10
///
///   # Write the database from whatever has been generated so far.
///   dart run tool/generate_dictionary.dart build
///
/// DeepSeek has no batch endpoint, so a 30k-word run is tens of thousands of
/// live HTTP calls and takes hours. Every finished word is appended to a cache
/// file immediately, so a crash, a rate limit, or Ctrl-C costs only the
/// requests that were in flight — never the whole run. `generate` skips words
/// already cached, so rerunning is always safe.
///
/// Requires DEEPSEEK_API_KEY in the environment.
library;

import 'dart:convert';
import 'dart:io';

import 'package:bla_bla_in_english/data/dictionary_assets.dart';

import 'deepseek_client.dart';
import 'dictionary_content.dart';
import 'write_dictionary.dart';

/// Append-only record of every word generated so far, one JSON object per line.
const String defaultCachePath = 'tool/.dictionary_cache.jsonl';

Future<void> main(List<String> args) async {
  if (args.isEmpty) {
    stderr.writeln('Usage: generate | status | build   (see the file header)');
    exit(64);
  }

  final options = _Options.parse(args.skip(1).toList());

  switch (args.first) {
    case 'generate':
      await _generate(options);
    case 'status':
      _status(options);
    case 'build':
      _build(options);
    default:
      stderr.writeln('Unknown command: ${args.first}');
      exit(64);
  }
}

// ------------------------------------------------------------------ status

/// Reports what the cache holds and what is still missing, without touching
/// the network. Run this before spending money on a long run.
void _status(_Options options) {
  final words = _readWords(options.wordsPath, limit: options.limit);
  final cache = GenerationCache(options.cachePath);
  final entries = cache.readAll();

  final cached = {for (final entry in entries) entry.word};
  final wanted = [for (final word in words) word.word];
  final missing = [
    for (final word in wanted)
      if (!cached.contains(word)) word,
  ];
  final extra = cached.difference(wanted.toSet());

  // Cached entries were validated when written, but the file is editable and
  // may have been generated by an older prompt, so check again.
  final invalid = <String, String>{};
  for (final entry in entries) {
    final problems = entry.validate();
    if (problems.isNotEmpty) invalid[entry.word] = problems.join('; ');
  }

  stdout
    ..writeln('Word list : ${options.wordsPath}  (${wanted.length} words)')
    ..writeln('Cache     : ${options.cachePath}  (${entries.length} entries)')
    ..writeln('')
    ..writeln('  done    : ${cached.length}')
    ..writeln('  missing : ${missing.length}')
    ..writeln('  invalid : ${invalid.length}')
    ..writeln('  not in the word list: ${extra.length}');

  if (invalid.isNotEmpty) {
    stdout.writeln('\nInvalid entries (delete their lines and rerun generate):');
    for (final entry in invalid.entries.take(10)) {
      stdout.writeln('  ${entry.key}: ${entry.value}');
    }
    if (invalid.length > 10) {
      stdout.writeln('  ... and ${invalid.length - 10} more');
    }
  }

  if (missing.isNotEmpty) {
    stdout
      ..writeln('\nNext missing words: ${missing.take(10).join(', ')}'
          '${missing.length > 10 ? ', ...' : ''}')
      ..writeln(DeepSeekClient.costEstimate(
        options.model,
        missing.length,
        batchSize: options.batchSize,
      ));
  }
}

// ---------------------------------------------------------------- generate

Future<void> _generate(_Options options) async {
  final apiKey = Platform.environment['DEEPSEEK_API_KEY'];
  if (apiKey == null || apiKey.isEmpty) {
    stderr.writeln('DEEPSEEK_API_KEY is not set.');
    exit(78);
  }

  final all = _readWords(options.wordsPath, limit: options.limit);
  final cache = GenerationCache(options.cachePath);
  final done = cache.completedWords();
  final todo = [
    for (final word in all)
      if (!done.contains(word.word)) word,
  ];

  stdout.writeln('${all.length} words requested, ${done.length} already '
      'cached, ${todo.length} to generate.');
  if (todo.isEmpty) {
    stdout.writeln('Nothing to do. Run "build" to write the database.');
    return;
  }
  stdout.writeln(DeepSeekClient.costEstimate(
    options.model,
    todo.length,
    batchSize: options.batchSize,
  ));
  stdout.writeln('Cache: ${options.cachePath}  (safe to interrupt)\n');

  final client = DeepSeekClient(apiKey: apiKey, model: options.model);
  final queue = _chunk(todo, options.batchSize);
  final failures = <String, String>{};
  var completed = 0;
  var abandoned = false;

  Future<void> worker() async {
    while (queue.isNotEmpty && !abandoned) {
      final batch = queue.removeAt(0);
      final ranks = {for (final input in batch) input.word: input.rank};

      try {
        final json = await client.completeJson(
          system: systemPrompt,
          prompt: userPromptFor([for (final input in batch) input.word]),
          maxTokens: options.maxTokensFor(batch.length),
        );
        final outcome = BatchOutcome.parse(json, requestedRanks: ranks);

        // Persist the good ones before anything else can go wrong. The rest are
        // recorded so a rerun retries exactly those words.
        for (final entry in outcome.entries) {
          cache.append(entry);
        }
        if (outcome.failures.length > 0) {
          print("outcome: ");
          print(outcome.failures);
        }
        failures.addAll(outcome.failures);
      } catch (error) {
        // A transport-level failure loses the whole batch, not just one word.
        for (final input in batch) {
          print("$error");
          failures[input.word] = '$error';
        }
        if (_isFatal('$error')) {
          // Retrying cannot help and every further request just burns time, so
          // stop every worker, not only this one.
          abandoned = true;
        }
      }

      completed += batch.length;
      stdout.write(
        '\r  $completed/${todo.length} words  (${failures.length} failed)   ',
      );
    }
  }

  try {
    await Future.wait([
      for (var i = 0; i < options.concurrency; i++) worker(),
    ]);
  } finally {
    client.close();
    await cache.close();
  }

  stdout.writeln('\n');
  _reportFailures(failures);
  stdout.writeln('Cached ${cache.completedWords().length} words in total.');
  stdout.writeln('Run "build" to write ${options.dbPath}.');
  if (failures.isNotEmpty) {
    stdout.writeln('Rerun "generate" to retry the ${failures.length} that '
        'failed — cached words are skipped.');
  }
}

// ------------------------------------------------------------------- build

void _build(_Options options) {
  final entries = GenerationCache(options.cachePath).readAll();
  if (entries.isEmpty) {
    stderr
        .writeln('Cache ${options.cachePath} is empty. Run "generate" first.');
    exit(1);
  }
  writeDictionary(entries, options.dbPath);
}

// ------------------------------------------------------------------- cache

/// The append-only generation cache. Public so it can be tested directly —
/// resuming correctly is the difference between losing minutes and losing a
/// multi-hour run.
///
/// JSONL rather than a database: appending a line is cheap and ordered, a
/// half-written final line is easy to detect and drop on read, and the file
/// stays greppable while a long run is still in progress.
class GenerationCache {
  GenerationCache(this.path);

  final String path;
  IOSink? _sink;

  Set<String> completedWords() => {for (final entry in readAll()) entry.word};

  List<WordEntry> readAll() {
    final file = File(path);
    if (!file.existsSync()) return [];

    final entries = <WordEntry>[];
    for (final (index, line) in file.readAsLinesSync().indexed) {
      if (line.trim().isEmpty) continue;
      try {
        final json = jsonDecode(line) as Map<String, Object?>;
        entries.add(
          WordEntry.fromJson(
            json,
            word: json['word']! as String,
            frequencyRank: json['frequency_rank']! as int,
          ),
        );
      } catch (_) {
        // Only the last line can plausibly be torn, by a kill mid-write.
        stderr.writeln('  (skipping unreadable cache line ${index + 1})');
      }
    }
    return entries;
  }

  void append(WordEntry entry) {
    final sink = _sink ??= File(path).openWrite(mode: FileMode.append);
    sink.writeln(
      jsonEncode({
        'word': entry.word,
        'frequency_rank': entry.frequencyRank,
        'sentences': [
          for (final sentence in entry.sentences)
            {
              'text': sentence.text,
              'correct': sentence.correct,
              'near': sentence.near,
              'wrong': sentence.wrong,
            },
        ],
      }),
    );
  }

  Future<void> close() async {
    final sink = _sink;
    if (sink == null) return;
    _sink = null;
    await sink.flush();
    await sink.close();
  }
}

// ------------------------------------------------------------------ shared

/// Errors that no amount of retrying will fix, so the run should stop rather
/// than march through the rest of the word list failing every batch.
bool _isFatal(String error) {
  const hopeless = [
    'Insufficient Balance', // out of credit
    'Authentication Fails', // bad key
    'invalid_request_error',
  ];
  return hopeless.any(error.contains);
}

/// Splits [words] into groups of at most [size], preserving order so batches
/// stay grouped by frequency.
List<List<_WordInput>> _chunk(List<_WordInput> words, int size) => [
      for (var i = 0; i < words.length; i += size)
        words.sublist(i, i + size > words.length ? words.length : i + size),
    ];

void _reportFailures(Map<String, String> failures) {
  if (failures.isEmpty) return;
  stderr.writeln('${failures.length} words failed:');
  for (final entry in failures.entries.take(20)) {
    stderr.writeln('  ${entry.key}: ${entry.value}');
  }
  if (failures.length > 20) {
    stderr.writeln('  ... and ${failures.length - 20} more');
  }
}

class _WordInput {
  const _WordInput(this.word, this.rank);
  final String word;
  final int rank;
}

/// Reads the frequency-ordered word list. Blank lines and `#` comments are
/// ignored; the rank is the position among the remaining lines.
List<_WordInput> _readWords(String path, {int? limit}) {
  final file = File(path);
  if (!file.existsSync()) {
    stderr.writeln('Word list not found: $path');
    exit(66);
  }

  final words = <_WordInput>[];
  var rank = 0;
  for (final line in const LineSplitter().convert(file.readAsStringSync())) {
    final word = line.trim();
    if (word.isEmpty ||
        word.startsWith('#') ||
        (word.length == 1 && !['a', 'i'].contains(word.toLowerCase()))) {
      continue;
    }
    words.add(_WordInput(word, ++rank));
    if (limit != null && words.length >= limit) break;
  }
  return words;
}

class _Options {
  const _Options({
    required this.wordsPath,
    required this.dbPath,
    required this.cachePath,
    required this.model,
    required this.concurrency,
    required this.batchSize,
    this.maxTokensOverride,
    this.limit,
  });

  final String wordsPath;
  final String dbPath;
  final String cachePath;
  final String model;
  final int concurrency;

  /// How many words go into a single request.
  final int batchSize;

  final int? maxTokensOverride;
  final int? limit;

  /// Room one word needs in the response.
  ///
  /// Measured output is around 900 tokens per word; the headroom covers wordier
  /// definitions. Getting this wrong is expensive — a response that hits the
  /// cap is truncated and the whole batch is lost, so it is deliberately
  /// generous. Unused budget costs nothing: output is billed per token
  /// produced, not per token reserved.
  static const int tokensPerWord = 1400;

  /// The response budget for a batch of [words] words.
  int maxTokensFor(int words) =>
      maxTokensOverride ?? 1000 + words * tokensPerWord;

  static _Options parse(List<String> args) {
    final values = <String, String>{};
    for (var i = 0; i < args.length - 1; i += 2) {
      values[args[i].replaceFirst(RegExp('^--'), '')] = args[i + 1];
    }

    int positive(String name, String fallback) {
      final value = int.tryParse(values[name] ?? fallback);
      if (value == null || value < 1) {
        stderr.writeln('--$name must be a positive integer.');
        exit(64);
      }
      return value;
    }

    return _Options(
      wordsPath: values['words'] ?? 'tool/words_sample.txt',
      dbPath: values['out'] ?? dictionaryAssetPath,
      cachePath: values['cache'] ?? defaultCachePath,
      model: values['model'] ?? DeepSeekClient.defaultModel,
      // High enough to keep a long run moving, low enough to stay under the
      // rate limit of a personal key. The client backs off on 429 anyway.
      concurrency: positive('concurrency', '6'),
      // Batching amortises the system prompt across words, which is most of the
      // input cost. Past roughly 20 the response gets long enough that a single
      // truncation or a dropped word starts costing more than the saving.
      batchSize: positive('batch-size', '10'),
      maxTokensOverride:
          values['max-tokens'] == null ? null : positive('max-tokens', '0'),
      limit: values['limit'] == null ? null : positive('limit', '0'),
    );
  }
}
